# TCL File Generated by Component Editor 18.1
# Tue Feb 11 10:50:30 CET 2020
# DO NOT MODIFY


# 
# streamFIFO "streamFIFO" v1.6
# Alberto Perro 2020.02.11.10:50:30
# FIFO Avalon ST bridge
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module streamFIFO
# 
set_module_property DESCRIPTION "FIFO Avalon ST bridge"
set_module_property NAME streamFIFO
set_module_property VERSION 1.6
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Alberto Perro"
set_module_property DISPLAY_NAME streamFIFO
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL streamFIFO
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file streamFIFO.v VERILOG PATH IP/StreamFifo/streamFIFO.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end fifo_data fifo_data Output 256
add_interface_port conduit_end fifo_write fifo_write Output 1
add_interface_port conduit_end fifo_send fifo_send Output 1


# 
# connection point Avalon_ST
# 
add_interface Avalon_ST avalon_streaming end
set_interface_property Avalon_ST associatedClock clock
set_interface_property Avalon_ST associatedReset reset
set_interface_property Avalon_ST dataBitsPerSymbol 8
set_interface_property Avalon_ST errorDescriptor ""
set_interface_property Avalon_ST firstSymbolInHighOrderBits true
set_interface_property Avalon_ST maxChannel 0
set_interface_property Avalon_ST readyLatency 0
set_interface_property Avalon_ST symbolsPerBeat 32
set_interface_property Avalon_ST ENABLED true
set_interface_property Avalon_ST EXPORT_OF ""
set_interface_property Avalon_ST PORT_NAME_MAP ""
set_interface_property Avalon_ST CMSIS_SVD_VARIABLES ""
set_interface_property Avalon_ST SVD_ADDRESS_GROUP ""

add_interface_port Avalon_ST asi_ready ready Output 1
add_interface_port Avalon_ST asi_valid valid Input 1
add_interface_port Avalon_ST asi_data data Input 256

